[package]
name = "media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
tokio = { workspace = true, features = ["process", "sync", "rt", "fs"] }
serde = { workspace = true }
serde_json.workspace = true
jiff.workspace = true
jsonwebtoken.workspace = true
walkdir.workspace = true
notify.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tempfile.workspace = true
proptest.workspace = true

[lints]
workspace = true
