FROM docker.io/library/node:22-bookworm@sha256:8a34c4ab3ea2c5cd194f07e317b2a8f09461d3c8b05c4e34c8ccd56d56024c4d

RUN apt-get update \
    && apt-get install -y --no-install-recommends libxml2-utils iproute2 \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json /

RUN npm ci --no-fund --no-audit && npm cache clean --force

ENV PATH="/node_modules/.bin:${PATH}"

WORKDIR /work
