[package]
name = "persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "migrate"] }
jiff.workspace = true
lru.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }

[dev-dependencies]
contracts.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tempfile.workspace = true

[lints]
workspace = true
