[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
persistence.workspace = true
media.workspace = true
metadata.workspace = true
services.workspace = true
jobs.workspace = true
api.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tower = { workspace = true, features = ["util"] }
axum = { workspace = true }
jiff = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
